config/routes.rb
Rails.application.routes.draw do
	root 'kittens#index'

	get 'page/dashboard',  as: :dashboard
	get 'page/about',      as: :about

	devise_for :users

	resources :kittens do
	  resources :bookings
	end

	put "kittens/:id/paws",       to: "kittens#paws",       as: :kitten_paws

	get "bookings/:id/payment",   to: "bookings#payment",   as: :booking_payment
	put "bookings/:id/paid",      to: "bookings#paid",      as: :paid_booking
	put "bookings/:id/confirm",   to: "bookings#confirm",   as: :confirm_booking
	put "bookings/:id/owner",     to: "bookings#owner",     as: :owner_booking
	put "bookings/:id/player",    to: "bookings#player",    as: :player_booking
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	belongs_to :user
	has_many_attached :images, dependent: :destroy
	has_many :bookings, dependent: :destroy
	validates :name, :breed, :daily_rate, presence: true
	validates :daily_rate, numericality: { greater_than: 0 }

	def self.active?
		self.active
	end

end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy, :paws]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @kittens = Kitten.where(active: true).order(:id)
  end

  def show
    if user_signed_in?
      @bookings_in = Booking.where(bookings: { kitten_id: @kitten.id} ).
                   joins(:kitten).where(kittens: { user_id: current_user.id} )
      @bookings_out = Booking.where(user_id: current_user.id).where(kitten_id: @kitten.id)
    else
      @bookings_in = false
      @bookings_out = false
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)
    @kitten.user_id = current_user.id

    respond_to do |format|
      if @kitten.save
        format.html { redirect_to @kitten, notice: 'Kitten was successfully created.' }
        format.json { render :show, status: :created, location: @kitten }
      else
        format.html { render :new }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @kitten.update(kitten_params)
        format.html { redirect_to @kitten, notice: 'Kitten was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitten }
      else
        format.html { render :edit }
        format.json { render json: @kitten.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @kitten.destroy
    respond_to do |format|
      format.html { redirect_to kittens_url, notice: 'Kitten was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def paws
    if @kitten.active
      @kitten.active = false
      state = "pawsed"
    else
      @kitten.active = true
      state = "unpawsed"
    end
    respond_to do |format|
      if @kitten.save
        format.html { redirect_to @kitten, notice: "Kitten was successfully #{state}." }
      else
        format.html { render :new }
      end
    end
  end

  private
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end

    def kitten_params
      params.require(:kitten).permit(:name, :breed, :description, :daily_rate, :active, :user_id , images: [])
    end

  def check_user
    if current_user.id != @kitten.user_id
      redirect_to root_url, alert: "That is not your kitten."
    end
  end
end

app/helpers/kittens_helper.rb
module KittensHelper

	def placekitten
		"https://placekitten.com/#{rand(200..400)}"
	end

	def card_image_url(kitten)
		if kitten.images.attached?
			url_for(kitten.images.first)
		else
			placekitten
		end
	end

end

app/views/kittens/_card.html.erb
<div class="kitten-card">
	<a href="<%= url_for(kitten_path(kitten)) %>">
		<div class="kitten-card-img" style="background-image: url(<%= card_image_url(kitten) %>)">
			<% if user_signed_in? && kitten.user_id == current_user.id %>
				<div class="icon-group text-center justify-content-between">
					<div class="icon">
						<%= app_icon "https://img.icons8.com/plasticine/25/000000/pencil.png", edit_kitten_path(kitten) %>
					</div>
					<div class="icon">
						<%= link_to image_tag('https://img.icons8.com/plasticine/25/000000/filled-trash.png'), kitten, class: "btn", role: "button", method: :delete, data: {confirm: 'Are you sure?'} %>
					</div>
				</div>
				<% if kitten.active == false %>
					<div class="kitten-pawsed">
						<div class="kitten-pawsed-flag">
							<h3>pawsed</h3>
						</div>
						<div class="kitten-pawsed-info">
							This kitten is currently marked as "inactive", people will be unable to request a booking.
						</div>
					</div>
				<% end %>
			<% end %>
		</div>

		<div class="card-body">
			<div class="kitten-name">
				<h4><%= kitten.name %></h4>
			</div>
			<div class="kitten-breed">
				<h5><%= kitten.breed %></h5>
			</div>
			<div class="kitten-price">
				<table>
					<tr>
						<th>Hourly</th>
						<td><%= number_to_currency(kitten.hourly_rate) %></td>
					</tr>
					<tr>
						<th>Daily</th>
						<td><%= number_to_currency(kitten.daily_rate) %></td>
					</tr>
				</table>
			</div>
		</div>
	</a>
</div>

app/views/kittens/_cards.html.erb
<div class="kitten-card">
	<a href="<%= url_for(kitten_path(kitten)) %>">
		<div class="kitten-card-img" style="background-image: url(<%= card_image_url(kitten) %>)">
				<% if kitten.active == false %>
					<div class="kitten-pawsed">
						<div class="kitten-pawsed-flag">
							<h3>pawsed</h3>
						</div>
						<div class="kitten-pawsed-info">
							This kitten is currently marked as "inactive", people will be unable to request a booking.
						</div>
					</div>
				<% end %>
		</div>

		<div class="card-body">
			<div class="kitten-name">
				<h4><%= kitten.name %></h4>
			</div>
			<div class="kitten-breed">
				<h5><%= kitten.breed %></h5>
			</div>
			<div class="kitten-business">
				<table>
					<tr>
						<th>Daily</th>
						<td><%= number_to_currency(kitten.daily_rate) %></td>
					</tr>
					<% if user_signed_in? && current_user.id == kitten.user_id && Booking.where(kitten_id: kitten.id).count > 0 %>
					<tr>
						<th>Bookings</th>
						<td><%= Booking.where(kitten_id: kitten.id).count %> requests</td>
					</tr>
					<% end %>
					<% if user_signed_in? && current_user.id != kitten.user_id %>
						<% if Booking.where(user_id: current_user.id).where(kitten_id: kitten.id).count > 0 %>
						<tr>
							<th>Requests</th>
							<td><%= Booking.where(user_id: current_user.id).where(kitten_id: kitten.id).count %> play dates</td>
						</tr>
							<% end %>
					<% end %>
				</table>
			</div>


		</div>
	</a>
</div>

app/views/kittens/_form.html.erb
<section class="container">
	<%= form_with(model: kitten, local: true) do |form| %>
	
	<% if kitten.errors.any? %>
		<div id="error_explanation" class="alert alert-warning alert-dismissible fade show" role="alert">
			<h5><%= pluralize(kitten.errors.count, "error") %> prohibited this kitten from being saved:</h5>
			<ul>
				<% kitten.errors.full_messages.each do |message| %>
					<li class="list-unstyled"><%= message %></li>
				<% end %>
			</ul>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	<% end %>
  <div class="form-group row">
    <%= form.label :name, class: "col-sm-2 col-form-label"  %>
	  <div class="input-group col-sm-4 mb-3">
    <%= form.text_field :name, class: "form-control", placeholder: "Kitten Name" %>
	  </div>
    <%= form.label :breed, class: "col-sm-2 col-form-label"  %>
	  <div class="input-group col-sm-4 mb-3">
    <%= form.text_field :breed, class: "form-control", placeholder: "Kitten Breed" %>
	  </div>
  </div>
  <div class="form-group row">
    <%= form.label :description, class: "col-sm-2 col-form-label"  %>
	  <div class="input-group  col-sm-10 mb-3">
    <%= form.text_area :description, class: "form-control" %>
	  </div>
  </div>
  <div class="form-group row">
    <%= form.label :daily_rate, class: "col-sm-2 col-form-label" %>
	  <div class="input-group col-sm-4 mb-3">
		  <div class="input-group-prepend">
			  <span class="input-group-text">$</span>
		  </div>
    <%= form.text_field :daily_rate, class: "form-control" %>
	  </div>
		<%= form.label :images, class: "col-sm-2 col-form-label"  %>
	  <div class="input-group col-sm-4 mb-3">
		  <div class="custom-file">
		<%= form.file_field :images, multiple: true, class:"custom-file-input",id:"inputGroupFile" %>
		  <label class="custom-file-label" for="inputGroupFile">Choose images.</label>
		  </div>
	  </div>
	</div>
	<% if kitten.images.attached? %>
		<%= render 'imagegallery' %>
	<% end %>
	<div class="form-group row d-flex justify-content-around">
    <%= form.submit class:"btn btn-outline-primary" %>
		<%= link_to 'Back', kittens_path, class: "btn btn-outline-primary" %>
  </div>
<% end %>
</section>

app/views/kittens/_imagegallery.html.erb
<div class="row" id="gallery" data-toggle="modal" data-target="#kittenModal">
	<% if @kitten.images.attached? %>
		<% @kitten.images.each_with_index do |img, index| %>
			<div class="col-6 col-sm-3 col-lg-1">
				<img
					src="<%= url_for(img) %>"
					alt="Gallery Image - <%= img.name %>"
					class="w-100"
					data-target="#kittenCarousel"
					data-slide-to="<%= index %>"/>
			</div>
		<% end %>
	<% else %>
		<div class="col-12 col-sm-6 col-lg-3">
			<%= image_tag placekitten, class: "w-100" %>
		</div>
	<% end %>
</div>

<!-- Modal markup: https://getbootstrap.com/docs/4.4/components/modal/ -->
<div class="modal fade" id="kittenModal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>
			<div class="modal-body">
				
				<!-- Carousel markup: https://getbootstrap.com/docs/4.4/components/carousel/ -->
				<div id="kittenCarousel" class="carousel slide" data-ride="carousel">
					<div class="carousel-inner">
						<% if @kitten.images.attached? %>
							<% @kitten.images.each_with_index do |img, index| %>
							<% if index == 0 %>
									<div class="carousel-item active">
										<img class="d-block w-100" src="<%= url_for(img) %>" alt="Gallery Image - <%= img.name %>">
									</div>
									<% else %>
									<div class="carousel-item">
										<img class="d-block w-100" src="<%= url_for(img) %>" alt="Gallery Image - <%= img.name %>">
									</div>
							<% end %>
							<% end %>
							<% else %>
							<div class="carousel-item active">
								<img class="d-block w-100" src="<%= placekitten %>" alt="Gallery Image">
							</div>
							<% end %>
					</div>
					<a class="carousel-control-prev" href="#kittenCarousel" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#kittenCarousel" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>
			</div>
			
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/kittens/dashboard.html.erb
<div class="dash-wrap">
	<div class="dash-left">
		<section class="dash-profile-details">
			<h2>Profile</h2>
			<div class="form-group row">
				<h5 class="col-sm-2">Name:</h5>
				<h6 class="col-sm-10"><%= current_user.name %></h6>
				<h5 class="col-sm-2">Email:</h5>
				<h6 class="col-sm-10"><%= current_user.email %></h6>
			</div>
			<div class="form-group row d-flex justify-content-between">
				<%= link_to "Edit details", edit_user_registration_path(current_user), class: "col-md-10 btn btn-primary btn-block" %>
				<%= link_to "Change password", edit_user_password_path(current_user), class: "col-md-10 btn btn-primary btn-block" %>
			</div>
		</section>
		<section class="dash-bookings">
			<h2>Play dates</h2>
<!--			TODO - Fix the code to show incoming booking requests-->
			<h5>Requested play dates</h5>
			<%= render 'bookings/booking-out', bookings_out: @bookings_out %>
			<h5>Booking requests</h5>
			<%= render 'bookings/booking-in', bookings_in: @bookings_in %>
		</section>
	</div>
<section class="dash-kitten-cards">
	<h2>Your Kittens</h2>
	<div class="form-group row d-flex justify-content-between">
		<%= link_to "New kitten", new_kitten_path, class: "btn btn-primary btn-block" %>
	</div>
	<div class="kitten-cards">
		<% @kittens.each do |kitten| %>
		<%= render 'cards', kitten: kitten %>
	<% end %>
		<% if !@kittens.any? %>
		<h6>You don't have any kittens yet. Please add a new one to your roster <%= link_to 'here', new_kitten_path %>.</h6>
			<% end %>
	</div>
</section>
</div>

app/views/kittens/edit.html.erb
<% @page_title = "Editing #{@kitten.name}" %>
<%= render 'form', kitten: @kitten %>

app/views/kittens/index.html.erb
<section class="kitten-cards" id="index">
	<% @kittens.each do |kitten| %>
			<%= render 'cards', kitten: kitten %>
	<% end %>
</section>

app/views/kittens/new.html.erb
<% @page_title = "New Kitten" %>
<%= render 'form', kitten: @kitten %>

app/views/kittens/owner.html.erb
<section class="kitten-cards">
	<% @kittens.each do |kitten| %>
		<%= render 'card', kitten: kitten %>
	<% end %>
</section>

app/views/kittens/show.html.erb
<% @page_title = @kitten.name %>


<section class="container kitten-details">
	<h2>Kitten Details</h2>
	<div class="row d-flex">
		<h5 class="col-sm-3">Owner</h5>
		<h6 class="col-sm-9"><%= @kitten.user.name %></h6>
		<h5 class="col-sm-3">Breed:</h5>
		<h6 class="col-sm-9"><%= @kitten.breed %></h6>
		<h5 class="col-sm-3">Daily rate</h5>
		<h6 class="col-sm-9"><%= number_to_currency(@kitten.daily_rate) %></h6>
		<h5 class="col-sm-3">Description</h5>
		<h6 class="col-sm-9"><%= @kitten.description %></h6>
	</div>
	<div class="row d-flex justify-content-around mb-3">
		<% if user_signed_in? && @kitten.user_id == current_user.id %>
			<%= link_to 'Edit', edit_kitten_path(@kitten), class:"btn btn-outline-primary" %>
			<%= link_to 'Delete', kitten_path(@kitten), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-primary" %>
			<% if @kitten.active %>
			<%= link_to 'Paws Kitten', kitten_paws_url(@kitten), method: :put, class:"btn btn-outline-primary" %>
				<% else %>
				<%= link_to 'Un-paws Kitten', kitten_paws_url(@kitten), method: :put, class:"btn btn-outline-primary" %>
				<% end %>
		<% end %>
		<%= link_to 'Back', _back_url, class:"btn btn-outline-primary" %>
	</div>
</section> <!-- kitten-details -->

<section class="container kitten-images">
	<h2>Kitten pictures</h2>
<%= render 'imagegallery' %>
</section>

<section class="container kitten-bookings">
	<h2>Bookings</h2>
	<% unless @bookings_in == false %>
	<% @bookings_in.each do |booking| %>
		<%= render "bookings/booking-in", booking: booking %>
	<% end %>
		<% end %>
	<% unless @bookings_out == false %>
	<% @bookings_out.each do |booking| %>
		<%= render "bookings/booking-out" , booking: booking %>
	<% end %>
		<% end %>
</section>

<section class="container kitten-requests">
<% unless user_signed_in? && @kitten.user_id == current_user.id %>
		<h2>Requests</h2>
	<%= render 'bookings/form' %>
<% end %>
</section>