config/routes.rb
Rails.application.routes.draw do
	root 'kittens#index'

	get 'page/dashboard',  as: :dashboard
	get 'page/about',      as: :about

	devise_for :users

	resources :kittens do
	  resources :bookings
	end

	put "kittens/:id/paws",       to: "kittens#paws",       as: :kitten_paws

	get "bookings/:id/payment",   to: "bookings#payment",   as: :booking_payment
	put "bookings/:id/paid",      to: "bookings#paid",      as: :paid_booking
	put "bookings/:id/confirm",   to: "bookings#confirm",   as: :confirm_booking
	put "bookings/:id/owner",     to: "bookings#owner",     as: :owner_booking
	put "bookings/:id/player",    to: "bookings#player",    as: :player_booking
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :kitten
  belongs_to :user
  validates :start_time, :end_time, presence: true
  validate :end_time_after_start_time

  private

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_date, "must be after the start date")
    end
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, except: [:new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :check_user, only: [:edit, :update, :destroy]

  def show
  end

  def new
    @booking = Booking.new
  end

  def edit
  end

  def create
    @kitten = Kitten.find(params[:kitten_id])
    @booking = @kitten.bookings.build(booking_params)
    @booking.user_id = current_user.id
    @booking.length_human = TimeDifference.between(@booking.start_time, @booking.end_time).humanize
    @booking.total = booking_charge
    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_payment_path(@booking),
                                  notice: 'Please process payment to secure your request.' }
      else
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Error when processing Booking request. Please try again.' }
      end
    end
  end

  def update
    @booking.length_human = TimeDifference.between(@booking.start_time, @booking.end_time).humanize
    @booking.total = booking_charge
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Booking was successfully updated.' }
      else
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Error when processing Booking change request. Please try again.' }
      end
    end
  end

  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to kitten_path(@kitten),
                                notice: 'Booking was successfully destroyed.' }
    end
  end

  def payment

  end

  def paid
    @booking.paid = true
    respond_to do |format|
      if @booking.save
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Thank you for your payment. Enjoy your play date.' }
      else
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Error when processing payment. Please try again.' }
      end
    end
  end

  def confirm
    @booking.confirmed = true
    respond_to do |format|
      if @booking.save
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Booking was successfully confirmed.' }
      else
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Error when processing Booking confirmation. Please try again.' }
      end
    end
  end

  def owner
    @booking.owner = true
    respond_to do |format|
      if @booking.save
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Booking was successfully completed. Payment will be released to you within 24-48 hours if the player has already confirmed completion.' }
      else
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Error when processing Booking completion. Please try again.' }
      end
    end
  end

  def player
    @booking.player = true
    respond_to do |format|
      if @booking.save
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Booking was successfully completed.' }
      else
        format.html { redirect_to kitten_path(@kitten),
                                  notice: 'Error when processing Booking completion. Please try again.' }
      end
    end
  end

  private

    def set_booking
      @booking = Booking.find(params[:id])
      @kitten = @booking.kitten_id
    end

    def booking_params
      params.require(:booking).permit(:kitten_id, :user_id, :length_human, :start_time, :end_time, :total,
                                      :paid, :confirmed, :owner, :player)
    end

  def check_user
    unless current_user.id == @booking.user_id or current_user.id == @booking.kitten.user_id
      redirect_to root_url, alert: "You are not authorised for this action."
    end
  end

  def booking_charge
    TimeDifference.between(@booking.start_time, @booking.end_time).in_days.ceil * @booking.kitten.daily_rate
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper

	def total(booking)
		number_to_currency(booking.total)
	end

	def state(booking)
		booking = booking

		if booking.start_time > DateTime.now
			future(booking)
		elsif booking.start_time < DateTime.now && booking.end_time > DateTime.now
			current(booking)
		elsif booking.end_time < DateTime.now
			past(booking)
		else
			"error BH100"
		end
	end

	def future(booking)
		if booking.paid == false
			"future-payment"
		elsif booking.confirmed == false
			"future-confirmation"
		elsif booking.paid && booking.confirmed
			"future-booked"
		else
			"error BH200"
		end
	end

	def current(booking)
		if booking.paid && booking.confirmed
			"current-confirmed"
		elsif booking.paid == false
			"cancelled-payment"
		elsif booking.confirmed == false
			"cancelled-confirmation"
		else
			"error BH300"
		end
	end
	#
	def past(booking)
		if booking.paid == false && booking.confirmed == false
			"error BH401"
		elsif booking.owner == false && booking.player == false
			"past-none"
		elsif booking.player == false
			"past-player"
		elsif booking.owner == false
			"past-owner"
		elsif booking.owner && booking.player
			if booking.fundsreleased == false
				"past-payment"
			elsif booking.fundsreleased
				"past-complete"
			else
				"error BH402"
			end
		else
			"error BH403"
		end
	end
	end

app/views/bookings/_booking-in-flags.html.erb
<div class="card-text text-center text-primary flex-column justify-content-center">
	<% state = state(booking) %>
	<% if state.start_with? "error" %>
		<h5>Please log a ticket <a href="https://github.com/miztrz/kitnappd/issues">here</a> and quote error code <%= state.delete_prefix("error ") %>. We will resolve this as soon as possible.</h5>
	<% elsif state == "future-payment" %>
		<h5>Pending payment, no action required.</h5>
	<% elsif state == "future-confirmation" %>
		<h5>Please confirm kitten availability.</h5>
		<%= link_to 'Confirm Booking', confirm_booking_url(booking), method: :put, class:"btn btn-primary" %>
	<% elsif state == "future-booked" %>
		<h5>Confirmed play date.</h5>
	<% elsif state == "current-confirmed" %>
		<h5>Active play date.</h5>
	<% elsif state == "cancelled-payment" %>
		<h5>Cancelled - Non payment.</h5>
		<%= link_to 'Delete Booking', kitten_booking_path(id: booking, kitten_id: booking.kitten_id), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
	<% elsif state == "cancelled-confirmation" %>
		<h5>You did not respond in time.</h5>
	<% elsif state == "past-none" || state == "past-owner" %>
		<h5>Please confirm your kitten has been returned to you in full health.</h5>
		<%= link_to 'Confirm Kitten Return', owner_booking_url(booking), method: :put, class:"btn btn-primary" %>
	<% elsif state == "past-player" %>
		<h5>Player pending confirmation of completed play date.</h5>
	<% elsif state == "past-payment" %>
		<h5>Payment release pending, expected 24-48 hour turnaround.</h5>
	<% elsif state == "past-complete" %>
		<h5>Complete.</h5>
		<%= link_to 'Delete Booking', kitten_booking_path(id: booking, kitten_id: booking.kitten_id), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
	<% else %>
		<h5>Please log a ticket <a href="https://github.com/miztrz/kitnappd/issues">here</a> and quote error code BH100. We will resolve this as soon as possible.</h5>
	<% end %>
</div>

app/views/bookings/_booking-in.html.erb
<% if @bookings_in.exists? %>
	<div class="booking-cards">
		<% @bookings_in.each do |booking| %>
			<div class="card border-primary booking-card">
				<a href="<%= url_for(kitten_path(booking.kitten.id)) %>">
					<div class="card-header d-flex justify-content-between">
						<h3><%= booking.kitten.name %></h3>
						<h4><%= number_to_currency(booking.total) %></h4>
					</div>
			</a>
					<div class="card-body">
						<div class="card-text d-flex justify-content-between text-white">
							<p>Requested By</p>
							<p><%= booking.user.name %></p>
						</div>
						<div class="card-text d-flex justify-content-between text-white">
							<p>Length of Booking</p>
							<p><%= booking.length_human %></p>
						</div>
						<div class="card-text d-flex justify-content-between text-white">
							<p>Start Date</p>
							<p><%= booking.start_time.strftime("%A %e %b %Y") %></p>
						</div>
						<div class="card-text d-flex justify-content-between text-white">
							<p>End Date</p>
							<p><%= booking.end_time.strftime("%A %e %b %Y") %></p>
						</div>
						<%= render 'bookings/booking-in-flags', booking: booking %>
		
					</div>
			</div>
		<% end %>
	</div>
<% else %>
	<h6>There are no booking requests for you yet.</h6>
<% end %>

app/views/bookings/_booking-out-flags.html.erb
<div class="card-text text-center text-primary row d-flex justify-content-center">
	<% state = state(booking) %>
	<% if state.start_with? "error" %>
		<h5>Please log a ticket <a href="https://github.com/miztrz/kitnappd/issues">here</a> and quote error code <%= state.delete_prefix("error ") %>. We will resolve this as soon as possible.</h5>
	<% elsif state == "future-payment" %>
		<h5>Please pay to secure this kitten.</h5>
		<%= link_to 'Payment', booking_payment_url(booking), method: :get, class:"btn btn-primary" %>
	<% elsif state == "future-confirmation" %>
		<h5>The kitten owner will confirm availability shortly. Thankyou for your patience.</h5>
	<% elsif state == "future-booked" %>
		<h5>Confirmed play date.</h5>
	<% elsif state == "current-confirmed" %>
		<h5>Active play date.</h5>
	<% elsif state == "cancelled-payment" %>
		<h5>Cancelled - Non payment.</h5>
		<%= link_to 'Delete Booking', kitten_booking_path(id: booking, kitten_id: booking.kitten_id), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
	<% elsif state == "cancelled-confirmation" %>
		<h5>Cancelled - The owner did not confirm. We will issue your refund within 24-48 hours.</h5>
		<%= link_to 'Delete Booking', kitten_booking_path(id: booking, kitten_id: booking.kitten_id), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
	<% elsif state == "past-none" || state == "past-player" %>
		<h5>Please confirm your play date was a success.</h5>
		<%= link_to 'Confirm Play Date', player_booking_url(booking), method: :put, class:"btn btn-primary" %>
	<% elsif state == "past-payment" || state == "past-owner" %>
		<h5>Complete.</h5>
	<% elsif state == "past-complete" %>
		<h5>Complete.</h5>
		<%= link_to 'Delete Booking', kitten_booking_path(id: booking, kitten_id: booking.kitten_id), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
	<% else %>
		<h5>Please log a ticket <a href="https://github.com/miztrz/kitnappd/issues">here</a> and quote error code BH100. We will resolve this as soon as possible.</h5>
	<% end %>
</div>

app/views/bookings/_booking-out.html.erb
<% if @bookings_out.exists? %>
	<div class="booking-cards">
		<% @bookings_out.each do |booking| %>
			<div class="card border-primary booking-card">
				<a href="<%= url_for(kitten_path(booking.kitten.id)) %>">
					<div class="card-header d-flex justify-content-between">
						<h3><%= booking.kitten.name %></h3>
						<h4><%= number_to_currency(booking.total) %></h4>
					</div>
				</a>
					<div class="card-body">
						<div class="card-text d-flex justify-content-between text-white">
							<p>Kitten Owner</p>
							<p><%= booking.kitten.user.name %></p>
						</div>
						<div class="card-text d-flex justify-content-between text-white">
						<p>Length of Booking</p>
							<p><%= booking.length_human %></p>
					</div>
					<div class="card-text d-flex justify-content-between text-white">
						<p>Start Date</p>
						<p><%= booking.start_time.strftime("%A %e %b %Y") %></p>
					</div>
					<div class="card-text d-flex justify-content-between text-white">
						<p>End Date</p>
						<p><%= booking.end_time.strftime("%A %e %b %Y") %></p>
					</div>
					<%= render 'bookings/booking-out-flags', booking: booking %>
				</div>
		</div>
	<% end %>
</div>
<% else %>
	<h6>You haven't requested any play dates yet! Please see available kittens <%= link_to 'here', kittens_path %>.</h6>
<% end %>

app/views/bookings/_form.html.erb
<%= form_with(model: [ @kitten, @kitten.bookings.build ], local: true) do |form| %>
  <div class="form-group row">
    <%= form.label 'Start date', class: "col-sm-2 col-form-label" %>
    <%= form.date_field :start_time, type:'date', class: "form-control col-sm-4" %>
    <%= form.label 'End date', class: "col-sm-2 col-form-label" %>
    <%= form.date_field :end_time, type:'date', class: "form-control col-sm-4" %>
  </div>
  <div class="row d-flex justify-content-center">
    <%= form.submit "Create booking", class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/bookings/payment.html.erb
<%= form_with model: @booking, url: paid_booking_path(@booking), method: :put do %>
	<%= submit_tag 'Confirm Payment', class:"btn btn-primary btn-block" %>
<% end %>