config/routes.rb
Rails.application.routes.draw do
	root 'kittens#index'

	get 'page/dashboard',  as: :dashboard
	get 'page/about',      as: :about

	devise_for :users

	resources :kittens do
	  resources :bookings
	end

	put "kittens/:id/paws",       to: "kittens#paws",       as: :kitten_paws

	get "bookings/:id/payment",   to: "bookings#payment",   as: :booking_payment
	put "bookings/:id/paid",      to: "bookings#paid",      as: :paid_booking
	put "bookings/:id/confirm",   to: "bookings#confirm",   as: :confirm_booking
	put "bookings/:id/owner",     to: "bookings#owner",     as: :owner_booking
	put "bookings/:id/player",    to: "bookings#player",    as: :player_booking
end

app/views/layouts/_alerts.html.erb
<% flash.each do |type, msg| %>
	<% if alert %>
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			<%= msg %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">x</span>
			</button>
		</div>
	<% elsif notice %>
		<div class="alert alert-info alert-dismissible fade show" role="alert">
			<%= msg %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">x</span>
			</button>
		</div>
	<% else %>
		<div class="alert alert-warning" role="alert">
			<%= type %><br>
			<%= msg %>
		</div>
	<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="text-center"><small class="text-muted">© <%= Date.today.year %> kitnappd</small></div>

app/views/layouts/_nav.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary" role="navigation">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
	<%= link_to 'kitnappd', root_path, class: "navbar-brand" %>
		<div class="collapse navbar-collapse" id="navbarToggler">
			<ul class="navbar-nav">
				<li class="dropdown-divider"></li>
				<li class="nav-item">
					<%= link_to 'About', about_path, class: 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Kittens Available', kittens_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to 'Add a New Kitten', new_kitten_path , class: "nav-link" %>
				</li>
				<li class="dropdown-divider"></li>
			</ul>
			<ul class="navbar-nav">
				<% if user_signed_in? %>
					<li class="nav-item">
						<%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %>
					</li>
					<li class="nav-item">
						<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
					</li>
				<% else %>
					<li class="nav-item">
						<%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
					</li>
					<li class="nav-item">
						<%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
					</li>
				<% end %>
			</ul>
		</div>
		<!--				TODO Search function in Nav bar-->
		<!--				<form class="form-inline my-2 my-lg-0">-->
		<!--					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
		<!--					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
		<!--				</form>-->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>kitnappd<% if defined?(@page_title) %> - <%= @page_title %><% end %></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Come rent a kitty today!">
	<meta name="keywords" content="kitten, rental, cute, kitnappd">
	<meta name="author" content="© Bianca Wilkinson (<%= Date.today.year %>)">
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
	<%= render 'layouts/nav' %>
</header>
<main>
	<%= render 'layouts/alerts' %>
	<% if defined?(@page_title) %>
		<section class="app-page-title">
			<h1 class="text-center"><%= @page_title %></h1>
		</section>
	<% end %>
	<%= yield %>
</main>
<footer class="footer">
	<%= render 'layouts/footer' %>
</footer>
</body>
</html>